exp_name: strat_four_identifiability_new
project_name: ankit_identifiability_CCI_final_run_new_12
checkpoint_dir: ./runs
comment: Experiment comment goes here
data:
  images_dir: /gpfs/u/home/GGRD/GGRDpdhm/scratch/coco/images/test2023
  use_full_image_path: false
  preprocess_images: false
  viewpoint_list: ['left', 'right']
  name_keys: ['name', 'viewpoint']
  crop_bbox: true
  image_size:
    - 480
    - 480
  test:
    anno_path: /gpfs/u/home/GGRD/GGRDpdhm/barn/miniconda3x86/envs/jupyter/leopard_group_3.json
    checkpoint_path: ''
    n_filter_min: 2
    n_subsample_max: 10
  train:
    anno_path: /gpfs/u/home/GGRD/GGRDpdhm/barn/miniconda3x86/envs/jupyter/leopard_train_strat_four.json
    n_filter_min: 3
    n_subsample_max: null
  val:
    anno_path: /gpfs/u/home/GGRD/GGRDpdhm/barn/miniconda3x86/envs/jupyter/leopard_group_3.json
    n_filter_min: 2
    n_subsample_max: 10
engine:
  num_workers: 2
  train_batch_size: 2
  valid_batch_size: 6
  epochs: 30
  seed: 42
  device: cuda
  use_wandb: false
  loss_module: arcface

scheduler_params:
  lr_start: 3.510988205019138e-05
  lr_max: 0.0003510988205019138
  lr_min: 1.755494102509569e-05
  lr_ramp_ep: 15
  lr_sus_ep: 0
  lr_decay: 0.8

model_params:
  model_name: efficientnetv2_rw_m
  use_fc: false
  fc_dim: 2048
  dropout: 0.0
  loss_module: arcface
  s: 40.27228179427104
  margin: 0.3035845476844968
  pretrained: true
  n_classes: 865 
  theta_zero: 0.785
  
test:
  fliplr: false
  fliplr_view: []
  batch_size: 8s
